/*
 * This file is generated by jOOQ.
*/
package matcheam.jooq.generate.tables.records;


import java.math.BigDecimal;
import java.time.LocalDate;

import javax.annotation.Generated;

import matcheam.jooq.generate.tables.Match;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchRecord extends UpdatableRecordImpl<MatchRecord> implements Record7<String, String, LocalDate, String, String, String, BigDecimal> {

    private static final long serialVersionUID = -1994214836;

    /**
     * Setter for <code>matcheam.match.identifier</code>.
     */
    public void setIdentifier(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>matcheam.match.identifier</code>.
     */
    public String getIdentifier() {
        return (String) get(0);
    }

    /**
     * Setter for <code>matcheam.match.place</code>.
     */
    public void setPlace(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>matcheam.match.place</code>.
     */
    public String getPlace() {
        return (String) get(1);
    }

    /**
     * Setter for <code>matcheam.match.date</code>.
     */
    public void setDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>matcheam.match.date</code>.
     */
    public LocalDate getDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>matcheam.match.start</code>.
     */
    public void setStart(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>matcheam.match.start</code>.
     */
    public String getStart() {
        return (String) get(3);
    }

    /**
     * Setter for <code>matcheam.match.time</code>.
     */
    public void setTime(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>matcheam.match.time</code>.
     */
    public String getTime() {
        return (String) get(4);
    }

    /**
     * Setter for <code>matcheam.match.level</code>.
     */
    public void setLevel(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>matcheam.match.level</code>.
     */
    public String getLevel() {
        return (String) get(5);
    }

    /**
     * Setter for <code>matcheam.match.maxplayers</code>.
     */
    public void setMaxplayers(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>matcheam.match.maxplayers</code>.
     */
    public BigDecimal getMaxplayers() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, LocalDate, String, String, String, BigDecimal> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, LocalDate, String, String, String, BigDecimal> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Match.MATCH.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Match.MATCH.PLACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field3() {
        return Match.MATCH.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Match.MATCH.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Match.MATCH.TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Match.MATCH.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return Match.MATCH.MAXPLAYERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getMaxplayers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value1(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value2(String value) {
        setPlace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value3(LocalDate value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value4(String value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value5(String value) {
        setTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value6(String value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value7(BigDecimal value) {
        setMaxplayers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord values(String value1, String value2, LocalDate value3, String value4, String value5, String value6, BigDecimal value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchRecord
     */
    public MatchRecord() {
        super(Match.MATCH);
    }

    /**
     * Create a detached, initialised MatchRecord
     */
    public MatchRecord(String identifier, String place, LocalDate date, String start, String time, String level, BigDecimal maxplayers) {
        super(Match.MATCH);

        set(0, identifier);
        set(1, place);
        set(2, date);
        set(3, start);
        set(4, time);
        set(5, level);
        set(6, maxplayers);
    }
}
