/**
 * This class is generated by jOOQ
 */
package matcheam.jooq.generate.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchRecord extends org.jooq.impl.TableRecordImpl<matcheam.jooq.generate.tables.records.MatchRecord> implements org.jooq.Record6<java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Time, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -650721868;

	/**
	 * Setter for <code>matcheam.match.identifier</code>.
	 */
	public void setIdentifier(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>matcheam.match.identifier</code>.
	 */
	public java.lang.String getIdentifier() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>matcheam.match.place</code>.
	 */
	public void setPlace(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>matcheam.match.place</code>.
	 */
	public java.lang.String getPlace() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>matcheam.match.date</code>.
	 */
	public void setDate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>matcheam.match.date</code>.
	 */
	public java.sql.Timestamp getDate() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>matcheam.match.gametime</code>.
	 */
	public void setGametime(java.sql.Time value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>matcheam.match.gametime</code>.
	 */
	public java.sql.Time getGametime() {
		return (java.sql.Time) getValue(3);
	}

	/**
	 * Setter for <code>matcheam.match.level</code>.
	 */
	public void setLevel(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>matcheam.match.level</code>.
	 */
	public java.lang.String getLevel() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>matcheam.match.maxplayers</code>.
	 */
	public void setMaxplayers(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>matcheam.match.maxplayers</code>.
	 */
	public java.lang.Integer getMaxplayers() {
		return (java.lang.Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Time, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Time, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return matcheam.jooq.generate.tables.Match.MATCH.IDENTIFIER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return matcheam.jooq.generate.tables.Match.MATCH.PLACE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return matcheam.jooq.generate.tables.Match.MATCH.DATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Time> field4() {
		return matcheam.jooq.generate.tables.Match.MATCH.GAMETIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return matcheam.jooq.generate.tables.Match.MATCH.LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return matcheam.jooq.generate.tables.Match.MATCH.MAXPLAYERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getIdentifier();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getPlace();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getDate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Time value4() {
		return getGametime();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getMaxplayers();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchRecord value1(java.lang.String value) {
		setIdentifier(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchRecord value2(java.lang.String value) {
		setPlace(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchRecord value3(java.sql.Timestamp value) {
		setDate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchRecord value4(java.sql.Time value) {
		setGametime(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchRecord value5(java.lang.String value) {
		setLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchRecord value6(java.lang.Integer value) {
		setMaxplayers(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MatchRecord values(java.lang.String value1, java.lang.String value2, java.sql.Timestamp value3, java.sql.Time value4, java.lang.String value5, java.lang.Integer value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MatchRecord
	 */
	public MatchRecord() {
		super(matcheam.jooq.generate.tables.Match.MATCH);
	}

	/**
	 * Create a detached, initialised MatchRecord
	 */
	public MatchRecord(java.lang.String identifier, java.lang.String place, java.sql.Timestamp date, java.sql.Time gametime, java.lang.String level, java.lang.Integer maxplayers) {
		super(matcheam.jooq.generate.tables.Match.MATCH);

		setValue(0, identifier);
		setValue(1, place);
		setValue(2, date);
		setValue(3, gametime);
		setValue(4, level);
		setValue(5, maxplayers);
	}
}
