/*
 * This file is generated by jOOQ.
*/
package matcheam.jooq.generate.tables.records;


import java.math.BigDecimal;
import java.sql.Time;
import java.sql.Timestamp;

import javax.annotation.Generated;

import matcheam.jooq.generate.tables.Match;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchRecord extends TableRecordImpl<MatchRecord> implements Record6<String, String, Timestamp, Time, String, BigDecimal> {

    private static final long serialVersionUID = 709091096;

    /**
     * Setter for <code>matcheam.match.identifier</code>.
     */
    public void setIdentifier(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>matcheam.match.identifier</code>.
     */
    public String getIdentifier() {
        return (String) get(0);
    }

    /**
     * Setter for <code>matcheam.match.place</code>.
     */
    public void setPlace(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>matcheam.match.place</code>.
     */
    public String getPlace() {
        return (String) get(1);
    }

    /**
     * Setter for <code>matcheam.match.date</code>.
     */
    public void setDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>matcheam.match.date</code>.
     */
    public Timestamp getDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>matcheam.match.gametime</code>.
     */
    public void setGametime(Time value) {
        set(3, value);
    }

    /**
     * Getter for <code>matcheam.match.gametime</code>.
     */
    public Time getGametime() {
        return (Time) get(3);
    }

    /**
     * Setter for <code>matcheam.match.level</code>.
     */
    public void setLevel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>matcheam.match.level</code>.
     */
    public String getLevel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>matcheam.match.maxplayers</code>.
     */
    public void setMaxplayers(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>matcheam.match.maxplayers</code>.
     */
    public BigDecimal getMaxplayers() {
        return (BigDecimal) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Timestamp, Time, String, BigDecimal> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, Timestamp, Time, String, BigDecimal> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Match.MATCH.IDENTIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Match.MATCH.PLACE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Match.MATCH.DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Time> field4() {
        return Match.MATCH.GAMETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Match.MATCH.LEVEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return Match.MATCH.MAXPLAYERS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIdentifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPlace();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Time value4() {
        return getGametime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLevel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getMaxplayers();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value1(String value) {
        setIdentifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value2(String value) {
        setPlace(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value3(Timestamp value) {
        setDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value4(Time value) {
        setGametime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value5(String value) {
        setLevel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord value6(BigDecimal value) {
        setMaxplayers(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MatchRecord values(String value1, String value2, Timestamp value3, Time value4, String value5, BigDecimal value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchRecord
     */
    public MatchRecord() {
        super(Match.MATCH);
    }

    /**
     * Create a detached, initialised MatchRecord
     */
    public MatchRecord(String identifier, String place, Timestamp date, Time gametime, String level, BigDecimal maxplayers) {
        super(Match.MATCH);

        set(0, identifier);
        set(1, place);
        set(2, date);
        set(3, gametime);
        set(4, level);
        set(5, maxplayers);
    }
}
