/**
 * This class is generated by jOOQ
 */
package matcheam.jooq.generate.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Match extends org.jooq.impl.TableImpl<matcheam.jooq.generate.tables.records.MatchRecord> {

	private static final long serialVersionUID = 987064207;

	/**
	 * The singleton instance of <code>matcheam.match</code>
	 */
	public static final matcheam.jooq.generate.tables.Match MATCH = new matcheam.jooq.generate.tables.Match();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<matcheam.jooq.generate.tables.records.MatchRecord> getRecordType() {
		return matcheam.jooq.generate.tables.records.MatchRecord.class;
	}

	/**
	 * The column <code>matcheam.match.identifier</code>.
	 */
	public final org.jooq.TableField<matcheam.jooq.generate.tables.records.MatchRecord, java.lang.String> IDENTIFIER = createField("identifier", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>matcheam.match.place</code>.
	 */
	public final org.jooq.TableField<matcheam.jooq.generate.tables.records.MatchRecord, java.lang.String> PLACE = createField("place", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>matcheam.match.date</code>.
	 */
	public final org.jooq.TableField<matcheam.jooq.generate.tables.records.MatchRecord, java.sql.Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>matcheam.match.gametime</code>.
	 */
	public final org.jooq.TableField<matcheam.jooq.generate.tables.records.MatchRecord, java.sql.Time> GAMETIME = createField("gametime", org.jooq.impl.SQLDataType.TIME.nullable(false), this, "");

	/**
	 * The column <code>matcheam.match.level</code>.
	 */
	public final org.jooq.TableField<matcheam.jooq.generate.tables.records.MatchRecord, java.lang.String> LEVEL = createField("level", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>matcheam.match.maxplayers</code>.
	 */
	public final org.jooq.TableField<matcheam.jooq.generate.tables.records.MatchRecord, java.lang.Integer> MAXPLAYERS = createField("maxplayers", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>matcheam.match</code> table reference
	 */
	public Match() {
		this("match", null);
	}

	/**
	 * Create an aliased <code>matcheam.match</code> table reference
	 */
	public Match(java.lang.String alias) {
		this(alias, matcheam.jooq.generate.tables.Match.MATCH);
	}

	private Match(java.lang.String alias, org.jooq.Table<matcheam.jooq.generate.tables.records.MatchRecord> aliased) {
		this(alias, aliased, null);
	}

	private Match(java.lang.String alias, org.jooq.Table<matcheam.jooq.generate.tables.records.MatchRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, matcheam.jooq.generate.Matcheam.MATCHEAM, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public matcheam.jooq.generate.tables.Match as(java.lang.String alias) {
		return new matcheam.jooq.generate.tables.Match(alias, this);
	}

	/**
	 * Rename this table
	 */
	public matcheam.jooq.generate.tables.Match rename(java.lang.String name) {
		return new matcheam.jooq.generate.tables.Match(name, null);
	}
}
