/**
 * This class is generated by jOOQ
 */
package matcheam.jooq.generate;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Matcheam extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1057288184;

	/**
	 * The singleton instance of <code>matcheam</code>
	 */
	public static final Matcheam MATCHEAM = new Matcheam();

	/**
	 * No further instances allowed
	 */
	private Matcheam() {
		super("matcheam");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			matcheam.jooq.generate.tables.Person.PERSON);
	}
}
