/*
 * This file is generated by jOOQ.
*/
package matcheam.jooq.generate;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in matcheam
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>matcheam.system_sequence_9080c586_8f83_4880_830e_66f629e14a56</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_9080C586_8F83_4880_830E_66F629E14A56 = new SequenceImpl<Long>("system_sequence_9080c586_8f83_4880_830e_66f629e14a56", Matcheam.MATCHEAM, org.jooq.impl.SQLDataType.BIGINT);
}
