/*
 * This file is generated by jOOQ.
*/
package matcheam.jooq.generate;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in matcheam
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>matcheam.system_sequence_9ef9681c_d859_483f_9451_c37ec57c6180</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_9EF9681C_D859_483F_9451_C37EC57C6180 = new SequenceImpl<Long>("system_sequence_9ef9681c_d859_483f_9451_c37ec57c6180", Matcheam.MATCHEAM, org.jooq.impl.SQLDataType.BIGINT);
}
