/*
 * This file is generated by jOOQ.
*/
package matcheam.jooq.generate;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in matcheam
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>matcheam.system_sequence_8149b6ae_80f8_4b06_83a2_f9f1a2573cf9</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_8149B6AE_80F8_4B06_83A2_F9F1A2573CF9 = new SequenceImpl<Long>("system_sequence_8149b6ae_80f8_4b06_83a2_f9f1a2573cf9", Matcheam.MATCHEAM, org.jooq.impl.SQLDataType.BIGINT);
}
