/*
 * This file is generated by jOOQ.
*/
package matcheam.jooq.generate;


import javax.annotation.Generated;

import matcheam.jooq.generate.tables.Match;


/**
 * Convenience access to all tables in matcheam
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>matcheam.match</code>.
     */
    public static final Match MATCH = matcheam.jooq.generate.tables.Match.MATCH;
}
