/**
 * This class is generated by jOOQ
 */
package matcheam.jooq.generate;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in matcheam
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table matcheam.match
	 */
	public static final matcheam.jooq.generate.tables.Match MATCH = matcheam.jooq.generate.tables.Match.MATCH;
}
