/**
 * This class is generated by jOOQ
 */
package nu.studer.sample.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Rights extends org.jooq.impl.TableImpl<nu.studer.sample.information_schema.tables.records.RightsRecord> {

	private static final long serialVersionUID = 711601808;

	/**
	 * The singleton instance of <code>INFORMATION_SCHEMA.RIGHTS</code>
	 */
	public static final nu.studer.sample.information_schema.tables.Rights RIGHTS = new nu.studer.sample.information_schema.tables.Rights();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<nu.studer.sample.information_schema.tables.records.RightsRecord> getRecordType() {
		return nu.studer.sample.information_schema.tables.records.RightsRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.GRANTEE</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.RightsRecord, java.lang.String> GRANTEE = createField("GRANTEE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.GRANTEETYPE</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.RightsRecord, java.lang.String> GRANTEETYPE = createField("GRANTEETYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.GRANTEDROLE</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.RightsRecord, java.lang.String> GRANTEDROLE = createField("GRANTEDROLE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.RIGHTS</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.RightsRecord, java.lang.String> RIGHTS_ = createField("RIGHTS", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.TABLE_SCHEMA</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.RightsRecord, java.lang.String> TABLE_SCHEMA = createField("TABLE_SCHEMA", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.TABLE_NAME</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.RightsRecord, java.lang.String> TABLE_NAME = createField("TABLE_NAME", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * The column <code>INFORMATION_SCHEMA.RIGHTS.ID</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.RightsRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.RIGHTS</code> table reference
	 */
	public Rights() {
		this("RIGHTS", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.RIGHTS</code> table reference
	 */
	public Rights(java.lang.String alias) {
		this(alias, nu.studer.sample.information_schema.tables.Rights.RIGHTS);
	}

	private Rights(java.lang.String alias, org.jooq.Table<nu.studer.sample.information_schema.tables.records.RightsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Rights(java.lang.String alias, org.jooq.Table<nu.studer.sample.information_schema.tables.records.RightsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, nu.studer.sample.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public nu.studer.sample.information_schema.tables.Rights as(java.lang.String alias) {
		return new nu.studer.sample.information_schema.tables.Rights(alias, this);
	}

	/**
	 * Rename this table
	 */
	public nu.studer.sample.information_schema.tables.Rights rename(java.lang.String name) {
		return new nu.studer.sample.information_schema.tables.Rights(name, null);
	}
}
