/**
 * This class is generated by jOOQ
 */
package nu.studer.sample.information_schema.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.1" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TableTypes extends org.jooq.impl.TableImpl<nu.studer.sample.information_schema.tables.records.TableTypesRecord> {

	private static final long serialVersionUID = 2026989922;

	/**
	 * The singleton instance of <code>INFORMATION_SCHEMA.TABLE_TYPES</code>
	 */
	public static final nu.studer.sample.information_schema.tables.TableTypes TABLE_TYPES = new nu.studer.sample.information_schema.tables.TableTypes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<nu.studer.sample.information_schema.tables.records.TableTypesRecord> getRecordType() {
		return nu.studer.sample.information_schema.tables.records.TableTypesRecord.class;
	}

	/**
	 * The column <code>INFORMATION_SCHEMA.TABLE_TYPES.TYPE</code>.
	 */
	public final org.jooq.TableField<nu.studer.sample.information_schema.tables.records.TableTypesRecord, java.lang.String> TYPE = createField("TYPE", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>INFORMATION_SCHEMA.TABLE_TYPES</code> table reference
	 */
	public TableTypes() {
		this("TABLE_TYPES", null);
	}

	/**
	 * Create an aliased <code>INFORMATION_SCHEMA.TABLE_TYPES</code> table reference
	 */
	public TableTypes(java.lang.String alias) {
		this(alias, nu.studer.sample.information_schema.tables.TableTypes.TABLE_TYPES);
	}

	private TableTypes(java.lang.String alias, org.jooq.Table<nu.studer.sample.information_schema.tables.records.TableTypesRecord> aliased) {
		this(alias, aliased, null);
	}

	private TableTypes(java.lang.String alias, org.jooq.Table<nu.studer.sample.information_schema.tables.records.TableTypesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, nu.studer.sample.information_schema.InformationSchema.INFORMATION_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public nu.studer.sample.information_schema.tables.TableTypes as(java.lang.String alias) {
		return new nu.studer.sample.information_schema.tables.TableTypes(alias, this);
	}

	/**
	 * Rename this table
	 */
	public nu.studer.sample.information_schema.tables.TableTypes rename(java.lang.String name) {
		return new nu.studer.sample.information_schema.tables.TableTypes(name, null);
	}
}
