CREATE SCHEMA IF NOT EXISTS matcheam;

CREATE TABLE matcheam.match (
identifier VARCHAR(100) PRIMARY KEY AUTO_INCREMENT,
place VARCHAR(100),
date DATE,
start VARCHAR(10),
time VARCHAR(10),
level VARCHAR(30),
maxPlayers DECIMAL(3)
);